# Generated by Django 3.2.8 on 2021-11-02 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectSite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_Paradym',
            field=models.BooleanField(default=False, verbose_name='Is Paradym'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_ThirdParty',
            field=models.BooleanField(default=False, verbose_name='Is ThirdParty'),
        ),
    ]
